kind: Deployment
apiVersion: apps/v1
metadata:
  name: kompass
  labels: 
    app: kompass
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kompass
  template:
    metadata:
      labels:
        app: kompass
    spec:
      containers:
        - name: metrics-provider
          image: josiahbjorgaard/kompass:latest
          ports:
            - name: http
              containerPort: 5000
