kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: kompass
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kompass
  minReplicas: 3
  maxReplicas: 30
  metrics:
  - type: Pods
    pods:
      metricName: flask_http_request_total
      targetAverageValue: 500m
