apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "class-ingress"
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: CLASS-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "flask"
              servicePort: 80
