apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kompass
  labels:
    app: kompass
spec:
  selector:
    matchLabels:
      app: kompass
  endpoints:
  - port: http
    interval: 5s
