apiVersion: v1
kind: Service
metadata:
  labels:
    app: kompass
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: kompass
spec:
  ports:
  - name: http
    port: 5000
  selector:
    app: kompass
